name: artic-rampart
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - biopython=1.70=np112py36_1
  - pandas=0.23.0=py36_1
  - minimap2=2.11
  - nodejs=10.8.0
  - pip=19.1
  - snakemake=5.4.3
  - watchdog=0.8.3=py36_0
  - pip:
    - msgpack==0.5.6
    - binlorry==0.1
    - git+https://github.com/artic-network/Porechop.git@v0.3.0pre