name: artic-rampart
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - nodejs=10.4.1
  - pip=19.1
  - yarn=1.10.1
  - snakemake=5.4.3
  - biopython=1.73
  - pandas=0.23.0=py36_1
  - python=3.6.6
  - minimap2=2.11
  - pip:
      - msgpack==0.5.6
    # mappy?
    # porechop (AR)?
