{% set version = "1.0.5" %}

package:
  name: rampart
  version: {{ version }}

source:
  url: https://github.com/artic-network/rampart/archive/v1.0.5.tar.gz
  folder: rampart
  sha256: ad11685e2ce3454afff726fe6f3105c97f6e5454a5be875a451870e058327344

requirements:
  build:
    - "nodejs>=10.4.1"
  run:
    - "nodejs>=10.4.1"

app:
  entry: rampart
  summary: "rampart"

build:
  number: 0
  noarch: generic

test:
  commands:
    - rampart --help

about:
  home: https://artic-network.github.io/rampart/
  license: AGPL-3.0-only
  summary: Read Assignment, Mapping, and Phylogenetic Analysis in Real Time
