{% set version = "1.0.1" %}

package:
  name: rampart
  version: {{ version }}

source:
  url: https://github.com/artic-network/rampart/archive/v1.0.1-1.tar.gz
  folder: rampart
  sha256: 424a9e60cc663234fcabe49b24c8e44a6900e86aa64b9e5d031e95644f3ef4a7

requirements:
  build:
    - "nodejs>=10.4.1"
  run:
    - "nodejs>=10.4.1"

app:
  entry: rampart
  summary: "rampart"

build:
  number: 0
  noarch: generic

test:
  commands:
    - rampart --help

about:
  home: https://artic-network.github.io/rampart/
  license: AGPL-3.0-only
  summary: Read Assignment, Mapping, and Phylogenetic Analysis in Real Time
