{% set version = "1.0.4" %}

package:
  name: rampart
  version: {{ version }}

source:
  url: https://github.com/artic-network/rampart/archive/v1.0.4.tar.gz
  folder: rampart
  sha256: d02ae76233cdc545ca94c454a38df43efad4f594855b63283f19190311f83a78

requirements:
  build:
    - "nodejs>=10.4.1"
  run:
    - "nodejs>=10.4.1"

app:
  entry: rampart
  summary: "rampart"

build:
  number: 0
  noarch: generic

test:
  commands:
    - rampart --help

about:
  home: https://artic-network.github.io/rampart/
  license: AGPL-3.0-only
  summary: Read Assignment, Mapping, and Phylogenetic Analysis in Real Time
